{% set version = "0.4" %}

package:
  name: otagrum
  version: {{ version }}

source:
  fn: otagrum-{{ version }}.tar.gz
  url: https://github.com/openturns/otagrum/archive/v{{ version }}.tar.gz
  sha256: 40d753d3395e8fa24c45d9f91f3af4e697f868b5e4f4ed488d98f584b07e2a65

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('otagrum', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - swig
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - curl  # [win]
  host:
    - python
    - openturns 1.16*
    - pyagrum
  run:
    - python
    - openturns 1.16*
    - pyagrum

test:
  imports:
    - otagrum

about:
  home: http://openturns.org/
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: OT/aGrUM module

extra:
  recipe-maintainers:
    - jschueller
