{% set version = "0.2" %}

package:
  name: otagrum
  version: {{ version }}

source:
  #fn: otagrum-{{ version }}.tar.gz
  #url: https://github.com/openturns/otagrum/archive/v{{ version }}.tar.gz
  #sha256: 853eff2e7ff59a03424c9b03bf9d508c59ccde668cc056a7da312170475bc30c

  # Use git waiting for the 0.2 release
  git_url: https://github.com/openturns/otagrum.git
  git_rev: 8ef711327cca94c4bb79cd78d36c2d3708095d69

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - cmake  # [not win]
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
  host:
    - python
    - swig  # [not win]
    - openturns  # [not win]
    - pyagrum  # [not win]
  run:
    - python
    - openturns
    - pyagrum

test:
  imports:
    - otagrum

about:
  home: http://openturns.org/
  license: LGPL3
  license_file: COPYING
  summary: OT/aGrUM module

extra:
  recipe-maintainers:
    - jschueller
