{% set version = "0.2" %}

package:
  name: otagrum
  version: {{ version }}

source:
  fn: otagrum-{{ version }}.tar.gz
  url: https://github.com/openturns/otagrum/archive/v{{ version }}.tar.gz
  sha256: dc0951152b6afd27064c508346f6e040a84df0c9da564a6e977f262a87dc3438

build:
  number: 7
  run_exports:
    - {{ pin_subpackage('otagrum', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - swig
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - curl  # [win]
  host:
    - python
    - openturns 1.15*
    - pyagrum
  run:
    - python
    - openturns 1.15*
    - pyagrum

test:
  imports:
    - otagrum

about:
  home: http://openturns.org/
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: OT/aGrUM module

extra:
  recipe-maintainers:
    - jschueller
