{% set version = "0.4" %}

package:
  name: otagrum
  version: {{ version }}

source:
  fn: otagrum-{{ version }}.tar.gz
  url: https://github.com/openturns/otagrum/archive/v{{ version }}.tar.gz
  sha256: 59ece6bbada835e575c6b09bbe600c9a3a37a6b07f86712d3eef65ea0b3b91a1

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('otagrum', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - swig
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - curl  # [win]
  host:
    - python
    - openturns 1.17*
    - pyagrum
  run:
    - python
    - openturns 1.17*
    - pyagrum
    - pyagrum 0.20.2  # [win]

test:
  imports:
    - otagrum

about:
  home: http://openturns.org/
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: OT/aGrUM module

extra:
  recipe-maintainers:
    - jschueller
