travis:
  secure:
    BINSTAR_TOKEN: r6LxUZZEPjuRMk3oAfmjqbxjjNXoEFExgaP8GN8/8sBi7OPx/Vj5kf4kZcyAAn6Gzbzj6IxSnnV80PjpeAeDGe6dZOs4Mb9CwBgLS58ZfqukIdPo244jpyUm+S/RJqb2jZIJnb1O5c6KUfY8nceRlWQpUhQCYuznj3dOGmdsT8VYrErhakbPhWqL5zryR8zH2dpjcpzPBY8B3P8mA5+Dr1NDrUXnwJBNW1uoep7JH14xGdtVtjhKyd3ZiYDuRivdldVMynA1qYwNNzb+vY7RzMtWcrLlJqumDn1VbBe2uFR16TFIMTafd2yi2PZOhATQGtYr/SjqLEKNJhwcAFICSO4VulJ+uTev0PZa9QKIwWFvP5hVk0VVWAfhZfsMpo3g8Ui2PegCJWdn7OOnKj/FnCb7998755cuNnJY3+5Pr+z5viY+CCgBWK1/2m4sHj5f7nxswUdwP6DKb85sLK9OH3K9nQ3ZMxpyO4je0qnoxI2M2MZrRgZXvy2iNdzTRJb75PEdQSERTmj2keulIeaSeYnXjuNLLbKaUnHLYt7/LtnwsndGVjkoVQxPmYsJ+o06OzSL+bZJmyAmMIz/qutjlm3f5mQ57xaZ/JHnRfpPZexik+6tm+1jKVx1gWOk//IA7rfVW/BuglM+oMqbvwzMOgKJDH9WtDtRLRht/ibuBjg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
